import { Book } from "./types";

export const BOOKS: Book[] = [
  { key: 'Mathayo', name: 'Mathayo', chapters: 28, color: 'text-orange-500', group: 'Gospel' },
  { key: 'Mariko', name: 'Mariko', chapters: 16, color: 'text-orange-500', group: 'Gospel' },
  { key: 'Luka', name: 'Luka', chapters: 24, color: 'text-orange-500', group: 'Gospel' },
  { key: 'Johana', name: 'Johana', chapters: 21, color: 'text-orange-500', group: 'Gospel' },
  { key: 'Tich Joote', name: 'Tich Joote', chapters: 28, color: 'text-cyan-500', group: 'History' },
  { key: 'Jo-Rumi', name: 'Jo-Rumi', chapters: 16, color: 'text-yellow-500', group: 'Epistle' },
  { key: '1 Jo-Korintho', name: '1 Jo-Korintho', chapters: 16, color: 'text-yellow-500', group: 'Epistle' },
  { key: '2 Jo-Korintho', name: '2 Jo-Korintho', chapters: 13, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jo-Galatia', name: 'Jo-Galatia', chapters: 6, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jo-Efeso', name: 'Jo-Efeso', chapters: 6, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jo-Filipi', name: 'Jo-Filipi', chapters: 4, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jo-Kolosai', name: 'Jo-Kolosai', chapters: 4, color: 'text-yellow-500', group: 'Epistle' },
  { key: '1 Jo-Thesalonika', name: '1 Jo-Thesalonika', chapters: 5, color: 'text-yellow-500', group: 'Epistle' },
  { key: '2 Jo-Thesalonika', name: '2 Jo-Thesalonika', chapters: 3, color: 'text-yellow-500', group: 'Epistle' },
  { key: '1 Timotheo', name: '1 Timotheo', chapters: 6, color: 'text-yellow-500', group: 'Epistle' },
  { key: '2 Timotheo', name: '2 Timotheo', chapters: 4, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Tito', name: 'Tito', chapters: 3, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Filemon', name: 'Filemon', chapters: 1, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jo-Hibrania', name: 'Jo-Hibrania', chapters: 13, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Jakobo', name: 'Jakobo', chapters: 5, color: 'text-yellow-500', group: 'Epistle' },
  { key: '1 Petro', name: '1 Petro', chapters: 5, color: 'text-yellow-500', group: 'Epistle' },
  { key: '2 Petro', name: '2 Petro', chapters: 3, color: 'text-yellow-500', group: 'Epistle' },
  { key: '1 Johana', name: '1 Johana', chapters: 5, color: 'text-yellow-500', group: 'Epistle' },
  { key: '2 Johana', name: '2 Johana', chapters: 1, color: 'text-yellow-500', group: 'Epistle' },
  { key: '3 Johana', name: '3 Johana', chapters: 1, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Juda', name: 'Juda', chapters: 1, color: 'text-yellow-500', group: 'Epistle' },
  { key: 'Fweny', name: 'Fweny', chapters: 22, color: 'text-yellow-500', group: 'Prophecy' },
];
