import { Book } from "./types";

export const BOOKS: Book[] = [
  { key: "Chakruok", name: "Chakruok", chapters: 50, color: "text-blue-400", group: "Pentateuch" },
  { key: "Wuok", name: "Wuok", chapters: 40, color: "text-blue-400", group: "Pentateuch" },
  { key: "Tim Jo-Lawi", name: "Tim Jo-Lawi", chapters: 27, color: "text-blue-400", group: "Pentateuch" },
  { key: "Kwan", name: "Kwan", chapters: 36, color: "text-blue-400", group: "Pentateuch" },
  { key: "Rapar Mar Chik", name: "Rapar Mar Chik", chapters: 34, color: "text-blue-400", group: "Pentateuch" },
  { key: "Joshua", name: "Joshua", chapters: 24, color: "text-emerald-400", group: "Old History" },
  { key: "Jong’ad Bura", name: "Jong’ad Bura", chapters: 21, color: "text-emerald-400", group: "Old History" },
  { key: "Ruth", name: "Ruth", chapters: 4, color: "text-emerald-400", group: "Old History" },
  { key: "1 Samuel", name: "1 Samuel", chapters: 31, color: "text-emerald-400", group: "Old History" },
  { key: "2 Samuel", name: "2 Samuel", chapters: 24, color: "text-emerald-400", group: "Old History" },
  { key: "1 Ruodhi", name: "1 Ruodhi", chapters: 22, color: "text-emerald-400", group: "Old History" },
  { key: "2 Ruodhi", name: "2 Ruodhi", chapters: 25, color: "text-emerald-400", group: "Old History" },
  { key: "1 Weche Mag Ndalo", name: "1 Weche Mag Ndalo", chapters: 29, color: "text-emerald-400", group: "Old History" },
  { key: "2 Weche Mag Ndalo", name: "2 Weche Mag Ndalo", chapters: 36, color: "text-emerald-400", group: "Old History" },
  { key: "Ezra", name: "Ezra", chapters: 10, color: "text-emerald-400", group: "Old History" },
  { key: "Nehemia", name: "Nehemia", chapters: 13, color: "text-emerald-400", group: "Old History" },
  { key: "Esta", name: "Esta", chapters: 10, color: "text-emerald-400", group: "Old History" },
  { key: "Ayub", name: "Ayub", chapters: 42, color: "text-purple-400", group: "Poetry" },
  { key: "Zaburi", name: "Zaburi", chapters: 150, color: "text-purple-400", group: "Poetry" },
  { key: "Ngeche", name: "Ngeche", chapters: 31, color: "text-purple-400", group: "Poetry" },
  { key: "Eklesiastes", name: "Eklesiastes", chapters: 12, color: "text-purple-400", group: "Poetry" },
  { key: "Wer Mamit", name: "Wer Mamit", chapters: 8, color: "text-purple-400", group: "Poetry" },
  { key: "Isaya", name: "Isaya", chapters: 66, color: "text-rose-400", group: "Major Prophets" },
  { key: "Jeremia", name: "Jeremia", chapters: 52, color: "text-rose-400", group: "Major Prophets" },
  { key: "Ywagruok", name: "Ywagruok", chapters: 5, color: "text-rose-400", group: "Major Prophets" },
  { key: "Ezekiel", name: "Ezekiel", chapters: 48, color: "text-rose-400", group: "Major Prophets" },
  { key: "Daniel", name: "Daniel", chapters: 12, color: "text-rose-400", group: "Major Prophets" },
  { key: "Hosea", name: "Hosea", chapters: 14, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Joel", name: "Joel", chapters: 3, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Amos", name: "Amos", chapters: 9, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Obadia", name: "Obadia", chapters: 1, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Jona", name: "Jona", chapters: 4, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Mika", name: "Mika", chapters: 7, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Nahum", name: "Nahum", chapters: 3, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Habakuk", name: "Habakuk", chapters: 3, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Zefania", name: "Zefania", chapters: 3, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Hagai", name: "Hagai", chapters: 2, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Zekaria", name: "Zekaria", chapters: 14, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Malaki", name: "Malaki", chapters: 4, color: "text-amber-400", group: "Minor Prophets" },
  { key: "Mathayo", name: "Mathayo", chapters: 28, color: "text-orange-500", group: "Gospel" },
  { key: "Mariko", name: "Mariko", chapters: 16, color: "text-orange-500", group: "Gospel" },
  { key: "Luka", name: "Luka", chapters: 24, color: "text-orange-500", group: "Gospel" },
  { key: "Johana", name: "Johana", chapters: 21, color: "text-orange-500", group: "Gospel" },
  { key: "Tich Joote", name: "Tich Joote", chapters: 28, color: "text-cyan-500", group: "History" },
  { key: "Jo-Rumi", name: "Jo-Rumi", chapters: 16, color: "text-yellow-500", group: "Epistle" },
  { key: "1 Jo-Korintho", name: "1 Jo-Korintho", chapters: 16, color: "text-yellow-500", group: "Epistle" },
  { key: "2 Jo-Korintho", name: "2 Jo-Korintho", chapters: 13, color: "text-yellow-500", group: "Epistle" },
  { key: "Jo-Galatia", name: "Jo-Galatia", chapters: 6, color: "text-yellow-500", group: "Epistle" },
  { key: "Jo-Efeso", name: "Jo-Efeso", chapters: 6, color: "text-yellow-500", group: "Epistle" },
  { key: "Jo-Filipi", name: "Jo-Filipi", chapters: 4, color: "text-yellow-500", group: "Epistle" },
  { key: "Jo-Kolosai", name: "Jo-Kolosai", chapters: 4, color: "text-yellow-500", group: "Epistle" },
  { key: "1 Jo-Thesalonika", name: "1 Jo-Thesalonika", chapters: 5, color: "text-yellow-500", group: "Epistle" },
  { key: "2 Jo-Thesalonika", name: "2 Jo-Thesalonika", chapters: 3, color: "text-yellow-500", group: "Epistle" },
  { key: "1 Timotheo", name: "1 Timotheo", chapters: 6, color: "text-yellow-500", group: "Epistle" },
  { key: "2 Timotheo", name: "2 Timotheo", chapters: 4, color: "text-yellow-500", group: "Epistle" },
  { key: "Tito", name: "Tito", chapters: 3, color: "text-yellow-500", group: "Epistle" },
  { key: "Filemon", name: "Filemon", chapters: 1, color: "text-yellow-500", group: "Epistle" },
  { key: "Jo-Hibrania", name: "Jo-Hibrania", chapters: 13, color: "text-yellow-500", group: "Epistle" },
  { key: "Jakobo", name: "Jakobo", chapters: 5, color: "text-yellow-500", group: "Epistle" },
  { key: "1 Petro", name: "1 Petro", chapters: 5, color: "text-yellow-500", group: "Epistle" },
  { key: "2 Petro", name: "2 Petro", chapters: 3, color: "text-yellow-500", group: "Epistle" },
  { key: "1 Johana", name: "1 Johana", chapters: 5, color: "text-yellow-500", group: "Epistle" },
  { key: "2 Johana", name: "2 Johana", chapters: 1, color: "text-yellow-500", group: "Epistle" },
  { key: "3 Johana", name: "3 Johana", chapters: 1, color: "text-yellow-500", group: "Epistle" },
  { key: "Juda", name: "Juda", chapters: 1, color: "text-yellow-500", group: "Epistle" },
  { key: "Fweny", name: "Fweny", chapters: 22, color: "text-yellow-500", group: "Prophecy" },
];
